In [ ]:
#Importing the packages
import pandas as pd
import numpy as np
from sklearn. feature_extraction. text import CountVectorizer
from sklearn. model_selection import train_test_split
from sklearn. tree import DecisionTreeClassifier

In [ ]:
import nltk
import re
nltk. download('stopwords')
from nltk. corpus import stopwords
stopword=set(stopwords.words('english'))
stemmer = nltk. SnowballStemmer("english")

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


In [ ]:
data = pd. read_csv("labeled_data.csv")
#To preview the data
print(data. head())

   Unnamed: 0  count  hate_speech  offensive_language  neither  class  \
0           0      3            0                   0        3      2   
1           1      3            0                   3        0      1   
2           2      3            0                   3        0      1   
3           3      3            0                   2        1      1   
4           4      6            0                   6        0      1   

                                               tweet  
0  !!! RT @mayasolovely: As a woman you shouldn't...  
1  !!!!! RT @mleew17: boy dats cold...tyga dwn ba...  
2  !!!!!!! RT @UrKindOfBrand Dawg!!!! RT @80sbaby...  
3  !!!!!!!!! RT @C_G_Anderson: @viva_based she lo...  
4  !!!!!!!!!!!!! RT @ShenikaRoberts: The shit you...  


In [ ]:
data["labels"] = data["class"]. map({0: "Hate Speech", 1: "Offensive Speech", 2: "No Hate and Offensive Speech"})
data = data[["tweet", "labels"]]
print(data. head())

                                               tweet  \
0  !!! RT @mayasolovely: As a woman you shouldn't...   
1  !!!!! RT @mleew17: boy dats cold...tyga dwn ba...   
2  !!!!!!! RT @UrKindOfBrand Dawg!!!! RT @80sbaby...   
3  !!!!!!!!! RT @C_G_Anderson: @viva_based she lo...   
4  !!!!!!!!!!!!! RT @ShenikaRoberts: The shit you...   

                         labels  
0  No Hate and Offensive Speech  
1              Offensive Speech  
2              Offensive Speech  
3              Offensive Speech  
4              Offensive Speech  


In [ ]:
data = data[['tweet', 'labels']]
data.head()

tweet  \
0  !!! RT @mayasolovely: As a woman you shouldn't...   
1  !!!!! RT @mleew17: boy dats cold...tyga dwn ba...   
2  !!!!!!! RT @UrKindOfBrand Dawg!!!! RT @80sbaby...   
3  !!!!!!!!! RT @C_G_Anderson: @viva_based she lo...   
4  !!!!!!!!!!!!! RT @ShenikaRoberts: The shit you...   

                         labels  
0  No Hate and Offensive Speech  
1              Offensive Speech  
2              Offensive Speech  
3              Offensive Speech  
4              Offensive Speech

In [ ]:
data.info

<bound method DataFrame.info of                                                    tweet  \
0      !!! RT @mayasolovely: As a woman you shouldn't...   
1      !!!!! RT @mleew17: boy dats cold...tyga dwn ba...   
2      !!!!!!! RT @UrKindOfBrand Dawg!!!! RT @80sbaby...   
3      !!!!!!!!! RT @C_G_Anderson: @viva_based she lo...   
4      !!!!!!!!!!!!! RT @ShenikaRoberts: The shit you...   
...                                                  ...   
24778  you's a muthaf***in lie &#8220;@LifeAsKing: @2...   
24779  you've gone and broke the wrong heart baby, an...   
24780  young buck wanna eat!!.. dat nigguh like I ain...   
24781              youu got wild bitches tellin you lies   
24782  ~~Ruffled | Ntac Eileen Dahlia - Beautiful col...   

                             labels  
0      No Hate and Offensive Speech  
1                  Offensive Speech  
2                  Offensive Speech  
3                  Offensive Speech  
4                  Offensive Speech  
...                

In [ ]:
def clean (text):
 text = str (text). lower()#lowercase
 text = re. sub('[.?]', '', text) 
 text = re. sub('https?://\S+|www.\S+', '', text)
 text = re. sub('<.?>+', '', text)
 text = re. sub('\n', '', text)
 text = re. sub('\w\d\w', '', text)
 text = [word for word in text.split(' ') if word not in stopword]
 text=" ". join(text)
 text = [stemmer. stem(word) for word in text. split(' ')]#stemming
 text=" ". join(text)
 return text
data["tweet"] = data["tweet"]. apply(clean)

In [ ]:
x = np. array(data["tweet"])
y = np. array(data["labels"])

# Vectorize the data (Converting text data in to matrix of token count)
cv = CountVectorizer()
X = cv. fit_transform(x)

# Splitting the Data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [ ]:
#Model building
model = DecisionTreeClassifier()
#Training the model
model. fit(X_train,y_train)

DecisionTreeClassifier()

In [ ]:
#Testing the model
y_pred = model. predict (X_test)
y_pred

array(['Offensive Speech', 'Offensive Speech',
       'No Hate and Offensive Speech', ..., 'Offensive Speech',
       'Offensive Speech', 'Offensive Speech'], dtype=object)

In [ ]:
#Accuracy Score of our model
from sklearn. metrics import accuracy_score
print (accuracy_score (y_test,y_pred))

0.8838488812813302


In [ ]:
inp = "You are awesome"
inp = cv. transform([inp]). toarray()
print(model. predict(inp))

['No Hate and Offensive Speech']


In [ ]:
inp = "You nigga"
inp = cv. transform([inp]). toarray()
print(model. predict(inp))

['Offensive Speech']


In [ ]:
inp = "the event is so beautifull"
inp = cv. transform([inp]). toarray()
print(model. predict(inp))

['No Hate and Offensive Speech']


In [ ]:
inp = "Fuck you"
inp = cv. transform([inp]). toarray()
print(model. predict(inp))

['Offensive Speech']


In [ ]:
# Confusion Matrix
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_pred))

[[ 169   52  244]
 [  29 1206  144]
 [ 262  204 5869]]


In [ ]:
# Precision
from sklearn.metrics import precision_score
print(precision_score(y_test, y_pred, average=None))

[0.3673913  0.8248974  0.93798945]


In [ ]:
# Accuracy
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, y_pred))

0.8856828463137303


In [ ]:
# Recall
from sklearn.metrics import recall_score
print(recall_score(y_test, y_pred, average=None))

[0.36344086 0.87454677 0.92644041]


In [ ]:
# f1 score
from sklearn.metrics import f1_score
print(f1_score(y_test, y_pred, average=None))

[0.36540541 0.84899683 0.93217916]
